"""quotes table

Revision ID: 905f0518f395
Revises: c43e99c4d7ad
Create Date: 2021-02-19 19:12:34.733924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905f0518f395'
down_revision = 'c43e99c4d7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_quote_author'), 'favorite_quote', ['author'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_quote_author'), table_name='favorite_quote')
    op.drop_table('favorite_quote')
    # ### end Alembic commands ###
